### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by charon-aesther** [charon-aesther/aesther-discord-bot#6]
## Features
- [x] Monorepo (turborepo) -> Please think about how to organize to the optimal(or suboptimal) architecture 
- [x] Logging + developer mode (or Dashboard?)
- [x] Modeling a DB for the archive streams 
- [x] HLS Player /  Making site where anyone can replay the streams (w/ Next.js)
- [x] Refactoring !

## Known issues
- [ ] Need to replace unavailable proxy servers(webshare.io)
- [ ] Something wrong in `@Lock` decorator -> figure out the issue
